### ISSUE TITLE
Unable to unregister protocol nette.safe://

### ISSUE THREAD

**Issue by greal** [nette/safe-stream#11]
Greetings!

A warning is displayed when a class is included:

```
Warning: stream_wrapper_unregister(): Unable to unregister protocol nette.safe:// in SafeStream\Wrapper.php on line 49
```

As far as I understand, this is an unnecessary denial.

https://github.com/nette/safe-stream/blob/c66cd83c3ae284c4a99aed0f647a2a3af3285bfe/src/SafeStream/Wrapper.php#L48

**Comment by ondrej-tuhacek** [comment]
Hi,

I ended up with this warning (making a console script) too. And I also think it should be without negation:

`if (in_array(self::PROTOCOL, stream_get_wrappers(), true)) { `

**Comment by dg** [comment]
Fixed, thanks
