### ISSUE TITLE
PHP 8.2: Creation of dynamic property Nette\Utils\SafeStream::$context is deprecated

### ISSUE THREAD

**Issue by Roman3349** [nette/safe-stream#12]
Version: 2.5.0

### Bug Description
```
E_DEPRECATED: Creation of dynamic property Nette\Utils\SafeStream::$context is deprecated
```

### Possible Solution
Could you please release version 2.5.1 with PHP 8.2 support added in https://github.com/nette/safe-stream/commit/9cba6c52f416017c15db35a94cc5c3a09a27f7a7 commit.

**Comment by dg** [comment]
Done
