### ISSUE TITLE
ignorace chmod

### ISSUE THREAD

**Issue by geniv** [nette/safe-stream#3]
Nebylo by na skodu implementovat stream_metadata() pro Chmod, kdyz se uz clovek snazi zmenit opravneni nad cestou se safe:// tak to konci: 
```php
chmod(): Nette\Utils\SafeStream::stream_metadata is not implemented!
```

**Comment by dg** [comment]
ping @geniv

**Comment by geniv** [comment]
Ja osobne ju neimplementoval, pri tom problemu se kterym jsem to resil (vylepseny Webloader) jsem to vyresil bez zasahu do SafeStreamu...

**Comment by dg** [comment]
A naimplementuješ?

**Comment by geniv** [comment]
pokud se k tomu dostanu tak bych mohl..., ale nic nechcu slibovat, momentalne resim nad nette vetsi komponenty ...

**Comment by geniv** [comment]
@dg implementovano, via pull request: https://github.com/nette/safe-stream/pull/5

**Comment by geniv** [comment]
@Majkl578 @dg je tady jeste neco zapotrebi? a nebo tam neco schazi?

**Comment by Majkl578** [comment]
@geniv: Tady asi ne, ale v tom PR nejsou dotažené testy (jsou za komentované?).

**Comment by geniv** [comment]
@Majkl578 jo jsou zakomentovane protoze je nedokaze Travis prechroustat...

**Comment by dg** [comment]
moved to #5
