### ISSUE TITLE
Commit 313134b8 bug

### ISSUE THREAD

**Issue by solcik** [nette/safe-stream#4]
Hello, 

commit 19871f2508 somehow broke usage of safe stream..
until this commit 313134b8d5 it is ok

Error message:
fopen(rs/...../webtemp/cssloader-4708361c72d3.css): failed to open stream: No such file or directory

**Comment by dg** [comment]
It should be fixed in commit 19871f2

**Comment by solcik** [comment]
The other way around:

"nette/safe-stream": "dev-master#313134b8d5" is working
"nette/safe-stream": "dev-master#19871f2508" is not

at least for me..

"nette/safe-stream": "dev-master#82f6bf623d" is ok - thank you.
