### ISSUE TITLE
Changes towards to support PHP 7.1

### ISSUE THREAD

**Issue by ondrejd** [nette/safe-stream#7]
Hi, I know that is important to support latest PHP versions, but why add something like `public const PROTOCOL = 'nette.safe';` - defaultly is constant PUBLIC and this is THE ONLY THING which makes latest version of nette/safe-stream incompatible with PHP 7.0.

Original change that causes this issue is here - https://github.com/nette/safe-stream/commit/282908f77802dd0f36f428b29e2986e173435fbc#r32225947

From my point of view this was a terrible update. I hope that you will also see `public const` is not neccessary "feature" and remove `public` keyword.

**Comment by vojtech-dobes** [comment]
I would argue that incompatibility with 7.0 *is the feature* (makes conceptual sense to me, but I don’t speak for the maintainer :) ).

**Comment by milo** [comment]
@ondrejd And the `void` return type hint? What exactly the problem is? There is a required PHP `7.1` in composer json, so how it is incompatible?

**Comment by ondrejd** [comment]
@milo Suprisingly `void` return type hint doesn't causes fault on PHP 7.0 but `public const` does. I know that is it **my mistake** but I'm so angry when I see these just _pro forma_ changes - there is **no sense** to add `public` before `const`.

**Comment by dg** [comment]
For PHP 7.0 use SameStream 2.3. For PHP 7.1 use SameStream 2.4.

Support for 2.3 is over (as well as support for PHP 7.0), support for 2.4 will continue. Don't be angry, be happy.

**Comment by milo** [comment]
@ondrejd PHP 7.0 understands `void` as a class name. It will load the source code but crash on method call.
Composer does not allow you to install 2.4 with PHP 7.0.
